// Generated by gencpp from file morai_msgs/Conveyor.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_CONVEYOR_H
#define MORAI_MSGS_MESSAGE_CONVEYOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct Conveyor_
{
  typedef Conveyor_<ContainerAllocator> Type;

  Conveyor_()
    : straight_reverse(0)
    , left_right(0)  {
    }
  Conveyor_(const ContainerAllocator& _alloc)
    : straight_reverse(0)
    , left_right(0)  {
  (void)_alloc;
    }



   typedef int32_t _straight_reverse_type;
  _straight_reverse_type straight_reverse;

   typedef int32_t _left_right_type;
  _left_right_type left_right;





  typedef boost::shared_ptr< ::morai_msgs::Conveyor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::Conveyor_<ContainerAllocator> const> ConstPtr;

}; // struct Conveyor_

typedef ::morai_msgs::Conveyor_<std::allocator<void> > Conveyor;

typedef boost::shared_ptr< ::morai_msgs::Conveyor > ConveyorPtr;
typedef boost::shared_ptr< ::morai_msgs::Conveyor const> ConveyorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::Conveyor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::Conveyor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::Conveyor_<ContainerAllocator1> & lhs, const ::morai_msgs::Conveyor_<ContainerAllocator2> & rhs)
{
  return lhs.straight_reverse == rhs.straight_reverse &&
    lhs.left_right == rhs.left_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::Conveyor_<ContainerAllocator1> & lhs, const ::morai_msgs::Conveyor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Conveyor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Conveyor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Conveyor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Conveyor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Conveyor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Conveyor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::Conveyor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29cf3f1705a2ed7d91592669dd89da67";
  }

  static const char* value(const ::morai_msgs::Conveyor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29cf3f1705a2ed7dULL;
  static const uint64_t static_value2 = 0x91592669dd89da67ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::Conveyor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/Conveyor";
  }

  static const char* value(const ::morai_msgs::Conveyor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::Conveyor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 straight_reverse\n"
"int32 left_right\n"
;
  }

  static const char* value(const ::morai_msgs::Conveyor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::Conveyor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.straight_reverse);
      stream.next(m.left_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Conveyor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::Conveyor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::Conveyor_<ContainerAllocator>& v)
  {
    s << indent << "straight_reverse: ";
    Printer<int32_t>::stream(s, indent + "  ", v.straight_reverse);
    s << indent << "left_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_CONVEYOR_H
