// Generated by gencpp from file morai_msgs/ExternalForce.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_EXTERNALFORCE_H
#define MORAI_MSGS_MESSAGE_EXTERNALFORCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct ExternalForce_
{
  typedef ExternalForce_<ContainerAllocator> Type;

  ExternalForce_()
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , force_x(0.0)
    , force_y(0.0)
    , force_z(0.0)  {
    }
  ExternalForce_(const ContainerAllocator& _alloc)
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , force_x(0.0)
    , force_y(0.0)
    , force_z(0.0)  {
  (void)_alloc;
    }



   typedef float _position_x_type;
  _position_x_type position_x;

   typedef float _position_y_type;
  _position_y_type position_y;

   typedef float _position_z_type;
  _position_z_type position_z;

   typedef float _force_x_type;
  _force_x_type force_x;

   typedef float _force_y_type;
  _force_y_type force_y;

   typedef float _force_z_type;
  _force_z_type force_z;





  typedef boost::shared_ptr< ::morai_msgs::ExternalForce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::ExternalForce_<ContainerAllocator> const> ConstPtr;

}; // struct ExternalForce_

typedef ::morai_msgs::ExternalForce_<std::allocator<void> > ExternalForce;

typedef boost::shared_ptr< ::morai_msgs::ExternalForce > ExternalForcePtr;
typedef boost::shared_ptr< ::morai_msgs::ExternalForce const> ExternalForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::ExternalForce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::ExternalForce_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::ExternalForce_<ContainerAllocator1> & lhs, const ::morai_msgs::ExternalForce_<ContainerAllocator2> & rhs)
{
  return lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.force_x == rhs.force_x &&
    lhs.force_y == rhs.force_y &&
    lhs.force_z == rhs.force_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::ExternalForce_<ContainerAllocator1> & lhs, const ::morai_msgs::ExternalForce_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ExternalForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ExternalForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ExternalForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ExternalForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ExternalForce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ExternalForce_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aefc97f66dbfb45872997157ecd3e94d";
  }

  static const char* value(const ::morai_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaefc97f66dbfb458ULL;
  static const uint64_t static_value2 = 0x72997157ecd3e94dULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/ExternalForce";
  }

  static const char* value(const ::morai_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::ExternalForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position_x\n"
"float32 position_y\n"
"float32 position_z\n"
"float32 force_x\n"
"float32 force_y\n"
"float32 force_z\n"
;
  }

  static const char* value(const ::morai_msgs::ExternalForce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::ExternalForce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.force_x);
      stream.next(m.force_y);
      stream.next(m.force_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExternalForce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::ExternalForce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::ExternalForce_<ContainerAllocator>& v)
  {
    s << indent << "position_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<float>::stream(s, indent + "  ", v.position_z);
    s << indent << "force_x: ";
    Printer<float>::stream(s, indent + "  ", v.force_x);
    s << indent << "force_y: ";
    Printer<float>::stream(s, indent + "  ", v.force_y);
    s << indent << "force_z: ";
    Printer<float>::stream(s, indent + "  ", v.force_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_EXTERNALFORCE_H
