// Generated by gencpp from file morai_msgs/RobotState.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_ROBOTSTATE_H
#define MORAI_MSGS_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : robot_state(0)
    , error_state(0)  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : robot_state(0)
    , error_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_state_type;
  _robot_state_type robot_state;

   typedef int32_t _error_state_type;
  _error_state_type error_state;





  typedef boost::shared_ptr< ::morai_msgs::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::morai_msgs::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::morai_msgs::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::morai_msgs::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::RobotState_<ContainerAllocator1> & lhs, const ::morai_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.robot_state == rhs.robot_state &&
    lhs.error_state == rhs.error_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::RobotState_<ContainerAllocator1> & lhs, const ::morai_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "835553f45e086a919a7670752929a6e8";
  }

  static const char* value(const ::morai_msgs::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x835553f45e086a91ULL;
  static const uint64_t static_value2 = 0x9a7670752929a6e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/RobotState";
  }

  static const char* value(const ::morai_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_state\n"
"int32 error_state\n"
;
  }

  static const char* value(const ::morai_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_state);
      stream.next(m.error_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "robot_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_state);
    s << indent << "error_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_ROBOTSTATE_H
