// Generated by gencpp from file morai_msgs/ShipCtrlCmd.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_SHIPCTRLCMD_H
#define MORAI_MSGS_MESSAGE_SHIPCTRLCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct ShipCtrlCmd_
{
  typedef ShipCtrlCmd_<ContainerAllocator> Type;

  ShipCtrlCmd_()
    : thrust(0.0)
    , rudder(0.0)  {
    }
  ShipCtrlCmd_(const ContainerAllocator& _alloc)
    : thrust(0.0)
    , rudder(0.0)  {
  (void)_alloc;
    }



   typedef float _thrust_type;
  _thrust_type thrust;

   typedef float _rudder_type;
  _rudder_type rudder;





  typedef boost::shared_ptr< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ShipCtrlCmd_

typedef ::morai_msgs::ShipCtrlCmd_<std::allocator<void> > ShipCtrlCmd;

typedef boost::shared_ptr< ::morai_msgs::ShipCtrlCmd > ShipCtrlCmdPtr;
typedef boost::shared_ptr< ::morai_msgs::ShipCtrlCmd const> ShipCtrlCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator2> & rhs)
{
  return lhs.thrust == rhs.thrust &&
    lhs.rudder == rhs.rudder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator1> & lhs, const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85d5dbe9a6145daec25dfb99701cfc26";
  }

  static const char* value(const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85d5dbe9a6145daeULL;
  static const uint64_t static_value2 = 0xc25dfb99701cfc26ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/ShipCtrlCmd";
  }

  static const char* value(const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 thrust\n"
"float32 rudder\n"
;
  }

  static const char* value(const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thrust);
      stream.next(m.rudder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShipCtrlCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::ShipCtrlCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::ShipCtrlCmd_<ContainerAllocator>& v)
  {
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
    s << indent << "rudder: ";
    Printer<float>::stream(s, indent + "  ", v.rudder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_SHIPCTRLCMD_H
