// Generated by gencpp from file morai_msgs/TOF.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_TOF_H
#define MORAI_MSGS_MESSAGE_TOF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct TOF_
{
  typedef TOF_<ContainerAllocator> Type;

  TOF_()
    : timestamp(0.0)
    , distance(0)  {
    }
  TOF_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , distance(0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::morai_msgs::TOF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::TOF_<ContainerAllocator> const> ConstPtr;

}; // struct TOF_

typedef ::morai_msgs::TOF_<std::allocator<void> > TOF;

typedef boost::shared_ptr< ::morai_msgs::TOF > TOFPtr;
typedef boost::shared_ptr< ::morai_msgs::TOF const> TOFConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::TOF_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::TOF_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::TOF_<ContainerAllocator1> & lhs, const ::morai_msgs::TOF_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::TOF_<ContainerAllocator1> & lhs, const ::morai_msgs::TOF_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::TOF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::TOF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::TOF_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::TOF_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::TOF_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::TOF_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::TOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fb9ac7b27b511cce0fecf3763a4d63e";
  }

  static const char* value(const ::morai_msgs::TOF_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fb9ac7b27b511ccULL;
  static const uint64_t static_value2 = 0xe0fecf3763a4d63eULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::TOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/TOF";
  }

  static const char* value(const ::morai_msgs::TOF_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::TOF_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timestamp\n"
"int32 distance\n"
;
  }

  static const char* value(const ::morai_msgs::TOF_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::TOF_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TOF_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::TOF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::TOF_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_TOF_H
