# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Msg/GNSS.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GNSS(genpy.Message):
  _md5sum = "a2a4beeb4c80c4affddeb8b52bbfae32"
  _type = "Msg/GNSS"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[3] EgoAccel
float32[3] IMUAccel
float32[3] EgoVel
float32[3] IMUVel
float32 EgoVelocity
float32 IMUVelocity"""
  __slots__ = ['EgoAccel','IMUAccel','EgoVel','IMUVel','EgoVelocity','IMUVelocity']
  _slot_types = ['float32[3]','float32[3]','float32[3]','float32[3]','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       EgoAccel,IMUAccel,EgoVel,IMUVel,EgoVelocity,IMUVelocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GNSS, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.EgoAccel is None:
        self.EgoAccel = [0.] * 3
      if self.IMUAccel is None:
        self.IMUAccel = [0.] * 3
      if self.EgoVel is None:
        self.EgoVel = [0.] * 3
      if self.IMUVel is None:
        self.IMUVel = [0.] * 3
      if self.EgoVelocity is None:
        self.EgoVelocity = 0.
      if self.IMUVelocity is None:
        self.IMUVelocity = 0.
    else:
      self.EgoAccel = [0.] * 3
      self.IMUAccel = [0.] * 3
      self.EgoVel = [0.] * 3
      self.IMUVel = [0.] * 3
      self.EgoVelocity = 0.
      self.IMUVelocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_3f().pack(*self.EgoAccel))
      buff.write(_get_struct_3f().pack(*self.IMUAccel))
      buff.write(_get_struct_3f().pack(*self.EgoVel))
      buff.write(_get_struct_3f().pack(*self.IMUVel))
      _x = self
      buff.write(_get_struct_2f().pack(_x.EgoVelocity, _x.IMUVelocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.EgoAccel = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.IMUAccel = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.EgoVel = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.IMUVel = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.EgoVelocity, _x.IMUVelocity,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.EgoAccel.tostring())
      buff.write(self.IMUAccel.tostring())
      buff.write(self.EgoVel.tostring())
      buff.write(self.IMUVel.tostring())
      _x = self
      buff.write(_get_struct_2f().pack(_x.EgoVelocity, _x.IMUVelocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.EgoAccel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.IMUAccel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.EgoVel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.IMUVel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 8
      (_x.EgoVelocity, _x.IMUVelocity,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
