# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/GVStateCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GVStateCmd(genpy.Message):
  _md5sum = "9c46684704317c52202cdb27e4bbbc62"
  _type = "morai_msgs/GVStateCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 latCtrlType
float32 targetLongitudinalVelocity
float32 targetAngularVelocity
float32[10] targetSteerAngle"""
  __slots__ = ['latCtrlType','targetLongitudinalVelocity','targetAngularVelocity','targetSteerAngle']
  _slot_types = ['int32','float32','float32','float32[10]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latCtrlType,targetLongitudinalVelocity,targetAngularVelocity,targetSteerAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GVStateCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latCtrlType is None:
        self.latCtrlType = 0
      if self.targetLongitudinalVelocity is None:
        self.targetLongitudinalVelocity = 0.
      if self.targetAngularVelocity is None:
        self.targetAngularVelocity = 0.
      if self.targetSteerAngle is None:
        self.targetSteerAngle = [0.] * 10
    else:
      self.latCtrlType = 0
      self.targetLongitudinalVelocity = 0.
      self.targetAngularVelocity = 0.
      self.targetSteerAngle = [0.] * 10

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2f().pack(_x.latCtrlType, _x.targetLongitudinalVelocity, _x.targetAngularVelocity))
      buff.write(_get_struct_10f().pack(*self.targetSteerAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.latCtrlType, _x.targetLongitudinalVelocity, _x.targetAngularVelocity,) = _get_struct_i2f().unpack(str[start:end])
      start = end
      end += 40
      self.targetSteerAngle = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2f().pack(_x.latCtrlType, _x.targetLongitudinalVelocity, _x.targetAngularVelocity))
      buff.write(self.targetSteerAngle.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.latCtrlType, _x.targetLongitudinalVelocity, _x.targetAngularVelocity,) = _get_struct_i2f().unpack(str[start:end])
      start = end
      end += 40
      self.targetSteerAngle = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=10)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
_struct_i2f = None
def _get_struct_i2f():
    global _struct_i2f
    if _struct_i2f is None:
        _struct_i2f = struct.Struct("<i2f")
    return _struct_i2f
