# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/ShipState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import morai_msgs.msg

class ShipState(genpy.Message):
  _md5sum = "48473abafb39e8611d0c7321f91ca943"
  _type = "morai_msgs/ShipState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 thrust
float32 rudder
GeoVector3Message position
GeoVector3Message rotation
GeoVector3Message velocity
GeoVector3Message angular_velocity
================================================================================
MSG: morai_msgs/GeoVector3Message
float64 x
float64 y
float64 z"""
  __slots__ = ['thrust','rudder','position','rotation','velocity','angular_velocity']
  _slot_types = ['float32','float32','morai_msgs/GeoVector3Message','morai_msgs/GeoVector3Message','morai_msgs/GeoVector3Message','morai_msgs/GeoVector3Message']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       thrust,rudder,position,rotation,velocity,angular_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShipState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.thrust is None:
        self.thrust = 0.
      if self.rudder is None:
        self.rudder = 0.
      if self.position is None:
        self.position = morai_msgs.msg.GeoVector3Message()
      if self.rotation is None:
        self.rotation = morai_msgs.msg.GeoVector3Message()
      if self.velocity is None:
        self.velocity = morai_msgs.msg.GeoVector3Message()
      if self.angular_velocity is None:
        self.angular_velocity = morai_msgs.msg.GeoVector3Message()
    else:
      self.thrust = 0.
      self.rudder = 0.
      self.position = morai_msgs.msg.GeoVector3Message()
      self.rotation = morai_msgs.msg.GeoVector3Message()
      self.velocity = morai_msgs.msg.GeoVector3Message()
      self.angular_velocity = morai_msgs.msg.GeoVector3Message()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f12d().pack(_x.thrust, _x.rudder, _x.position.x, _x.position.y, _x.position.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = morai_msgs.msg.GeoVector3Message()
      if self.rotation is None:
        self.rotation = morai_msgs.msg.GeoVector3Message()
      if self.velocity is None:
        self.velocity = morai_msgs.msg.GeoVector3Message()
      if self.angular_velocity is None:
        self.angular_velocity = morai_msgs.msg.GeoVector3Message()
      end = 0
      _x = self
      start = end
      end += 104
      (_x.thrust, _x.rudder, _x.position.x, _x.position.y, _x.position.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z,) = _get_struct_2f12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f12d().pack(_x.thrust, _x.rudder, _x.position.x, _x.position.y, _x.position.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = morai_msgs.msg.GeoVector3Message()
      if self.rotation is None:
        self.rotation = morai_msgs.msg.GeoVector3Message()
      if self.velocity is None:
        self.velocity = morai_msgs.msg.GeoVector3Message()
      if self.angular_velocity is None:
        self.angular_velocity = morai_msgs.msg.GeoVector3Message()
      end = 0
      _x = self
      start = end
      end += 104
      (_x.thrust, _x.rudder, _x.position.x, _x.position.y, _x.position.z, _x.rotation.x, _x.rotation.y, _x.rotation.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z,) = _get_struct_2f12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f12d = None
def _get_struct_2f12d():
    global _struct_2f12d
    if _struct_2f12d is None:
        _struct_2f12d = struct.Struct("<2f12d")
    return _struct_2f12d
