# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from morai_msgs/UGVServeSkidCtrlCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class UGVServeSkidCtrlCmd(genpy.Message):
  _md5sum = "4f54afce325790f6ec15cfae04a11605"
  _type = "morai_msgs/UGVServeSkidCtrlCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 steer_mode
float32 forward
float32 skid_steering
float32 ackermann_steering
float32 ackermann_steering_rear_ratio
"""
  __slots__ = ['steer_mode','forward','skid_steering','ackermann_steering','ackermann_steering_rear_ratio']
  _slot_types = ['int32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       steer_mode,forward,skid_steering,ackermann_steering,ackermann_steering_rear_ratio

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UGVServeSkidCtrlCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.steer_mode is None:
        self.steer_mode = 0
      if self.forward is None:
        self.forward = 0.
      if self.skid_steering is None:
        self.skid_steering = 0.
      if self.ackermann_steering is None:
        self.ackermann_steering = 0.
      if self.ackermann_steering_rear_ratio is None:
        self.ackermann_steering_rear_ratio = 0.
    else:
      self.steer_mode = 0
      self.forward = 0.
      self.skid_steering = 0.
      self.ackermann_steering = 0.
      self.ackermann_steering_rear_ratio = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i4f().pack(_x.steer_mode, _x.forward, _x.skid_steering, _x.ackermann_steering, _x.ackermann_steering_rear_ratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.steer_mode, _x.forward, _x.skid_steering, _x.ackermann_steering, _x.ackermann_steering_rear_ratio,) = _get_struct_i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i4f().pack(_x.steer_mode, _x.forward, _x.skid_steering, _x.ackermann_steering, _x.ackermann_steering_rear_ratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.steer_mode, _x.forward, _x.skid_steering, _x.ackermann_steering, _x.ackermann_steering_rear_ratio,) = _get_struct_i4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i4f = None
def _get_struct_i4f():
    global _struct_i4f
    if _struct_i4f is None:
        _struct_i4f = struct.Struct("<i4f")
    return _struct_i4f
