(cl:in-package morai_msgs-msg)
(cl:export '(LATCTRLTYPE-VAL
          LATCTRLTYPE
          TARGETLONGITUDINALVELOCITY-VAL
          TARGETLONGITUDINALVELOCITY
          TARGETANGULARVELOCITY-VAL
          TARGETANGULARVELOCITY
          TARGETSTEERANGLE-VAL
          TARGETSTEERANGLE
))