(cl:in-package morai_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          UNIQUE_ID-VAL
          UNIQUE_ID
          ACCELERATION-VAL
          ACCELERATION
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          HEADING-VAL
          HEADING
          ACCEL-VAL
          ACCEL
          BRAKE-VAL
          BRAKE
          WHEEL_ANGLE-VAL
          WHEEL_ANGLE
          WHEEL_ANGLE_REAR-VAL
          WHEEL_ANGLE_REAR
          WHEEL_SPEED_FL-VAL
          WHEEL_SPEED_FL
          WHEEL_SPEED_FR-VAL
          WHEEL_SPEED_FR
          WHEEL_SPEED_RL-VAL
          WHEEL_SPEED_RL
          WHEEL_SPEED_RR-VAL
          WHEEL_SPEED_RR
))